using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.Serialization;

namespace LightMiniGame.CardEditor
{
    /// <summary>
    /// 卡牌数据 —— 编辑器配置的核心 ScriptableObject。
    /// 普通形态和低理智形态两套完整数据，理智 <= 4 时自动切换为低理智形态。
    /// </summary>
    [CreateAssetMenu(menuName = "CardEditor/Card Entry", fileName = "NewCard")]
    public class CardEntry : ScriptableObject, ISerializationCallbackReceiver
    {
        // === 基础信息 ===
        [Header("基础信息")]
        [Tooltip("唯一 ID（不可为空，不可重复）")]
        public string cardId = "";

        [Tooltip("卡牌名称")]
        public string cardName = "";

        [Tooltip("普通形态描述")]
        [TextArea(2, 4)]
        [FormerlySerializedAs("baseDescription")]
        public string normalDescription = "";

        [Tooltip("低理智形态描述（理智 <= 4 时使用）")]
        [TextArea(2, 4)]
        [FormerlySerializedAs("upgradeDescription")]
        public string lowSanityDescription = "";

        [Tooltip("底层：卡面原画（卡牌最底层的卡面美术）")]
        public Sprite cardArt;

        [Tooltip("中层：描述框（卡名与描述所在框体美术）")]
        public Sprite descBoxSprite;

        [Tooltip("顶层：类型框（卡牌类型标签框体美术，如「攻击」）")]
        public Sprite typeBoxSprite;

        [Header("描述框位置（导出预制体时应用）")]
        [Tooltip("描述框中心水平偏移（像素，相对卡牌中心；0=用模板布局）")]
        public float descBoxOffsetX = -1f;

        [Tooltip("描述框底部距卡牌底部距离（像素，向上为正；0=用模板布局）")]
        public float descBoxOffsetY = 90f;

        [Tooltip("描述框高度（像素；0=用模板高度）")]
        public float descBoxHeight = 95f;

        [Tooltip("描述框左右内缩（像素，负值=外扩；0=用模板内缩）")]
        public float descBoxInset = 10f;

        [Tooltip("品级")]
        public CardGrade grade = CardGrade.Bronze;

        [Tooltip("卡牌类型")]
        public CardType cardType = CardType.Attack;

        [Tooltip("存在形式（普通形态）")]
        public CardExistence existence = CardExistence.Normal;

        [Tooltip("存在形式（低理智形态），默认与普通形态相同")]
        public CardExistence lowSanityExistence = CardExistence.Normal;

        [Tooltip("普通形态费用")]
        [FormerlySerializedAs("baseCost")]
        public int normalCost = 1;

        [Tooltip("低理智形态费用")]
        [FormerlySerializedAs("upgradeCost")]
        public int lowSanityCost = 1;

        [Tooltip("商店售价（金币）")]
        public int price = 10;

        [Tooltip("词条（可多选，同时生效）")]
        public CardKeyword keyword = CardKeyword.None;
        [SerializeField] private bool keywordsAreFlags;

        [Tooltip("是否配置低理智形态")]
        [FormerlySerializedAs("upgradable")]
        public bool hasLowSanityForm = true;

        // === 效果 ===
        [Header("效果")]
        [Tooltip("普通形态效果列表（按顺序依次结算）")]
        [FormerlySerializedAs("baseEffects")]
        public List<EffectNode> normalEffectNodes = new List<EffectNode>();

        [Tooltip("低理智形态效果列表（独立完整的一套效果，非差值）")]
        [FormerlySerializedAs("upgradeEffects")]
        public List<EffectNode> lowSanityEffectNodes = new List<EffectNode>();

        // === 自定义 ===
        [Header("自定义")]
        [Tooltip("自定义卡牌脚本（处理整张卡的特殊流程）")]
        public CustomCardScript customCardScript;

        // === 备注 ===
        [Header("备注")]
        [Tooltip("策划备注")]
        [TextArea(2, 4)]
        public string designerNotes = "";

        // === 便捷方法 ===

        public int GetCost(bool lowSanity) => lowSanity ? lowSanityCost : normalCost;

        public CardExistence GetExistence(bool lowSanity) => lowSanity ? lowSanityExistence : existence;

        public string GetDescription(bool lowSanity)
        {
            string desc = lowSanity ? lowSanityDescription : normalDescription;
            if (string.IsNullOrWhiteSpace(desc)) return AutoGenerateDescription(lowSanity);
            return ResolveDescriptionTemplate(desc, 0, 0);
        }

        /// <summary>
        /// 生成带属性解析的描述文本（力量/敏捷引用替换为实际数值）。
        /// 若配置了自定义描述文本（normalDescription/lowSanityDescription），解析其中的 {N+力量}/{N+敏捷} 模板后返回。
        /// 否则用 EffectNode.GetResolvedDescription 生成带数值的描述。
        /// </summary>
        public string GetResolvedDescription(bool lowSanity, int strength, int dexterity, bool isEnemy = false)
        {
            string desc = lowSanity ? lowSanityDescription : normalDescription;
            if (!string.IsNullOrWhiteSpace(desc))
                return ResolveDescriptionTemplate(desc, strength, dexterity);

            var sb = new StringBuilder();
            var effects = GetEffectNodes(lowSanity);
            for (int i = 0; i < effects.Count; i++)
            {
                if (!effects[i].enabled) continue;
                sb.AppendLine($"{i + 1}. {effects[i].GetResolvedDescription(strength, dexterity, isEnemy)}");
            }
            var ex = GetExistence(lowSanity);
            if (ex != CardExistence.Normal)
                sb.AppendLine(ex == CardExistence.BattleRemove ? "（战斗内移除）" : "（永久移除）");
            return sb.ToString().TrimEnd();
        }

        public List<EffectNode> GetEffectNodes(bool lowSanity)
            => lowSanity ? lowSanityEffectNodes : normalEffectNodes;

        public bool HasEffectNodes(bool lowSanity)
            => GetEffectNodes(lowSanity) is { Count: > 0 };

        public bool ShouldUseLowSanityForm(int currentSanity, int threshold = 4)
            => hasLowSanityForm && currentSanity <= threshold;

        public string AutoGenerateDescription(bool lowSanity)
        {
            var sb = new StringBuilder();
            var effects = GetEffectNodes(lowSanity);
            for (int i = 0; i < effects.Count; i++)
            {
                if (!effects[i].enabled) continue;
                sb.AppendLine($"{i + 1}. {effects[i].GetDescription()}");
            }
            var ex = GetExistence(lowSanity);
            if (ex != CardExistence.Normal)
                sb.AppendLine(ex == CardExistence.BattleRemove ? "（战斗内移除）" : "（永久移除）");
            return sb.ToString().TrimEnd();
        }

        // === 静态辅助 ===
        public static string GetGradeName(CardGrade g) => g switch
        {
            CardGrade.Bronze => "铜", CardGrade.Silver => "银", CardGrade.Gold => "金", _ => g.ToString()
        };
        public static string GetCardTypeName(CardType t) => t switch
        {
            CardType.Attack => "攻击", CardType.Skill => "技能", CardType.Ability => "能力", _ => t.ToString()
        };
        public static string GetExistenceName(CardExistence e) => e switch
        {
            CardExistence.Normal => "普通", CardExistence.BattleRemove => "战斗内移除", CardExistence.PermanentRemove => "永久移除", _ => e.ToString()
        };
        public static string GetKeywordName(CardKeyword k)
        {
            var names = CardKeywords.GetNames((KeywordType)(int)k);
            return names.Count == 0 ? "无" : string.Join("  ", names);
        }

        /// <summary>旧版单选序号 → 位标。1=股神…9=监控目标；其它值原样保留。</summary>
        public static CardKeyword SequentialToFlags(int old) => old switch
        {
            1 => CardKeyword.StockGod,
            2 => CardKeyword.Leek,
            3 => CardKeyword.Recycle,
            4 => CardKeyword.Accessory,
            5 => CardKeyword.Consult,
            6 => CardKeyword.InternalPrice,
            7 => CardKeyword.Bribe,
            8 => CardKeyword.Slack,
            9 => CardKeyword.WatchTarget,
            _ => (CardKeyword)old
        };

        public void OnBeforeSerialize() => keywordsAreFlags = true;

        public void OnAfterDeserialize()
        {
            if (keywordsAreFlags) return;
            keyword = SequentialToFlags((int)keyword);
            keywordsAreFlags = true;
        }

        // === 描述模板解析 ===

        /// <summary>
        /// 解析描述文本中的 {N+属性名} 动态模板，将占位符替换为实际计算值。
        /// 支持格式：{12+力量}→12+strength, {6-力量}→6-strength, {力量}→strength, {12}→12
        /// </summary>
        public static string ResolveDescriptionTemplate(string desc, int strength, int dexterity)
        {
            if (string.IsNullOrEmpty(desc)) return desc;

            var sb = new StringBuilder(desc.Length + 16);
            int i = 0;
            while (i < desc.Length)
            {
                if (desc[i] == '{')
                {
                    int close = desc.IndexOf('}', i + 1);
                    if (close < 0) { sb.Append(desc[i]); i++; continue; }

                    string expr = desc.Substring(i + 1, close - i - 1).Trim();
                    sb.Append(ResolveTemplateExpr(expr, strength, dexterity));
                    i = close + 1;
                }
                else
                {
                    sb.Append(desc[i]);
                    i++;
                }
            }
            return sb.ToString();
        }

        /// <summary>解析单个模板表达式，如 "12+力量" → 12 + strength</summary>
        private static int ResolveTemplateExpr(string expr, int strength, int dexterity)
        {
            if (string.IsNullOrEmpty(expr)) return 0;
            expr = expr.Trim();

            // 查找运算符（跳过开头的负号）
            int opIdx = -1;
            char op = '+';
            for (int i = 1; i < expr.Length; i++)
            {
                if (expr[i] == '+' || expr[i] == '-')
                {
                    opIdx = i;
                    op = expr[i];
                    break;
                }
            }

            if (opIdx > 0)
            {
                string left = expr.Substring(0, opIdx).Trim();
                string right = expr.Substring(opIdx + 1).Trim();
                int leftVal = ResolveTemplateTerm(left, strength, dexterity);
                int rightVal = ResolveTemplateTerm(right, strength, dexterity);
                return op == '+' ? leftVal + rightVal : leftVal - rightVal;
            }

            return ResolveTemplateTerm(expr, strength, dexterity);
        }

        private static int ResolveTemplateTerm(string term, int strength, int dexterity)
        {
            term = term.Trim();
            if (term == "力量") return strength;
            if (term == "敏捷") return dexterity;
            return int.TryParse(term, out int v) ? v : 0;
        }
    }
}
