using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.Serialization;

namespace LightMiniGame.CardEditor
{
    /// <summary>
    /// 卡牌数据 —— 编辑器配置的核心 ScriptableObject。
    /// 普通形态和低理智形态两套完整数据，理智 <= 4 时自动切换为低理智形态。
    /// </summary>
    [CreateAssetMenu(menuName = "CardEditor/Card Entry", fileName = "NewCard")]
    public class CardEntry : ScriptableObject
    {
        // === 基础信息 ===
        [Header("基础信息")]
        [Tooltip("唯一 ID（不可为空，不可重复）")]
        public string cardId = "";

        [Tooltip("卡牌名称")]
        public string cardName = "";

        [Tooltip("普通形态描述")]
        [TextArea(2, 4)]
        [FormerlySerializedAs("baseDescription")]
        public string normalDescription = "";

        [Tooltip("低理智形态描述（理智 <= 4 时使用）")]
        [TextArea(2, 4)]
        [FormerlySerializedAs("upgradeDescription")]
        public string lowSanityDescription = "";

        [Tooltip("卡面原画（普通形态）")]
        public Sprite cardArt;

        [Tooltip("黑暗卡面（低理智形态时替换为这张图）")]
        public Sprite darkCardArt;

        [Tooltip("品级")]
        public CardGrade grade = CardGrade.Bronze;

        [Tooltip("卡牌类型")]
        public CardType cardType = CardType.Attack;

        [Tooltip("存在形式（普通形态）")]
        public CardExistence existence = CardExistence.Normal;

        [Tooltip("普通形态费用")]
        [FormerlySerializedAs("baseCost")]
        public int normalCost = 1;

        [Tooltip("低理智形态费用")]
        [FormerlySerializedAs("upgradeCost")]
        public int lowSanityCost = 1;

        [Tooltip("商店售价（金币）")]
        public int price = 10;

        [Tooltip("词条（普通形态）")]
        public CardKeyword keyword = CardKeyword.None;

        [Tooltip("是否配置低理智形态")]
        [FormerlySerializedAs("upgradable")]
        public bool hasLowSanityForm = true;

        // === 效果 ===
        [Header("效果")]
        [Tooltip("普通形态效果列表（按顺序依次结算）")]
        [FormerlySerializedAs("baseEffects")]
        public List<EffectNode> normalEffectNodes = new List<EffectNode>();

        [Tooltip("低理智形态效果列表（独立完整的一套效果，非差值）")]
        [FormerlySerializedAs("upgradeEffects")]
        public List<EffectNode> lowSanityEffectNodes = new List<EffectNode>();

        // === 自定义 ===
        [Header("自定义")]
        [Tooltip("自定义卡牌脚本（处理整张卡的特殊流程）")]
        public CustomCardScript customCardScript;

        // === 备注 ===
        [Header("备注")]
        [Tooltip("策划备注")]
        [TextArea(2, 4)]
        public string designerNotes = "";

        // === 便捷方法 ===

        public int GetCost(bool lowSanity) => lowSanity ? lowSanityCost : normalCost;

        public string GetDescription(bool lowSanity)
        {
            string desc = lowSanity ? lowSanityDescription : normalDescription;
            return string.IsNullOrWhiteSpace(desc) ? AutoGenerateDescription(lowSanity) : desc;
        }

        public List<EffectNode> GetEffectNodes(bool lowSanity)
            => lowSanity ? lowSanityEffectNodes : normalEffectNodes;

        public bool HasEffectNodes(bool lowSanity)
            => GetEffectNodes(lowSanity) is { Count: > 0 };

        public bool ShouldUseLowSanityForm(int currentSanity, int threshold = 4)
            => hasLowSanityForm && currentSanity <= threshold;

        public string AutoGenerateDescription(bool lowSanity)
        {
            var sb = new StringBuilder();
            var effects = GetEffectNodes(lowSanity);
            for (int i = 0; i < effects.Count; i++)
            {
                if (!effects[i].enabled) continue;
                sb.AppendLine($"{i + 1}. {effects[i].GetDescription()}");
            }
            if (existence != CardExistence.Normal)
                sb.AppendLine(existence == CardExistence.BattleRemove ? "（战斗内移除）" : "（永久移除）");
            return sb.ToString().TrimEnd();
        }

        // === 静态辅助 ===
        public static string GetGradeName(CardGrade g) => g switch
        {
            CardGrade.Bronze => "铜", CardGrade.Silver => "银", CardGrade.Gold => "金", _ => g.ToString()
        };
        public static string GetCardTypeName(CardType t) => t switch
        {
            CardType.Attack => "攻击", CardType.Skill => "技能", CardType.Ability => "能力", _ => t.ToString()
        };
        public static string GetExistenceName(CardExistence e) => e switch
        {
            CardExistence.Normal => "普通", CardExistence.BattleRemove => "战斗内移除", CardExistence.PermanentRemove => "永久移除", _ => e.ToString()
        };
        public static string GetKeywordName(CardKeyword k) => k switch
        {
            CardKeyword.None => "无", CardKeyword.Echo => "回响", CardKeyword.Calamity => "灾厄", CardKeyword.Fate => "命运", _ => k.ToString()
        };
    }
}
