using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace LightMiniGame.CardEditor
{
    /// <summary>
    /// 卡牌数据 —— 编辑器配置的核心 ScriptableObject。
    /// 采用「基础效果数据化 + 复杂逻辑绑定脚本」的混合方案。
    /// </summary>
    [CreateAssetMenu(menuName = "CardEditor/Card Entry", fileName = "NewCard")]
    public class CardEntry : ScriptableObject
    {
        // === 基础信息 ===
        [Header("基础信息")]
        [Tooltip("唯一 ID（不可为空，不可重复）")]
        public string cardId = "";

        [Tooltip("卡牌名称")]
        public string cardName = "";

        [Tooltip("基础描述")]
        [TextArea(2, 4)]
        public string baseDescription = "";

        [Tooltip("升级后描述")]
        [TextArea(2, 4)]
        public string upgradeDescription = "";

        [Tooltip("卡面原画")]
        public Sprite cardArt;

        [Tooltip("黑暗卡面（理智转阶段时替换为这张图）")]
        public Sprite darkCardArt;

        [Tooltip("品级")]
        public CardGrade grade = CardGrade.Bronze;

        [Tooltip("卡牌类型")]
        public CardType cardType = CardType.Attack;

        [Tooltip("存在形式")]
        public CardExistence existence = CardExistence.Normal;

        [Tooltip("基础费用")]
        public int baseCost = 1;

        [Tooltip("升级后费用")]
        public int upgradeCost = 1;

        [Tooltip("词条")]
        public CardKeyword keyword = CardKeyword.None;

        [Tooltip("是否可以升级")]
        public bool upgradable = true;

        // === 效果 ===
        [Header("效果")]
        [Tooltip("基础效果列表（按顺序依次结算）")]
        public List<CardEffect> baseEffects = new List<CardEffect>();

        [Tooltip("升级效果列表（独立完整的一套效果，非差值）")]
        public List<CardEffect> upgradeEffects = new List<CardEffect>();

        // === 能力（仅能力卡使用） ===
        [Header("能力")]
        [Tooltip("基础能力数据（卡牌类型为「能力」时使用）")]
        public AbilityData baseAbility = new AbilityData();

        [Tooltip("升级能力数据（卡牌类型为「能力」时使用）")]
        public AbilityData upgradeAbility = new AbilityData();

        // === 自定义 ===
        [Header("自定义")]
        [Tooltip("自定义卡牌脚本（处理整张卡的特殊流程）")]
        public CustomCardScript customCardScript;

        // === 备注 ===
        [Header("备注")]
        [Tooltip("策划备注")]
        [TextArea(2, 4)]
        public string designerNotes = "";

        // === 便捷方法 ===

        /// <summary>获取当前费用（基础或升级）</summary>
        public int GetCost(bool upgraded) => upgraded ? upgradeCost : baseCost;

        /// <summary>获取当前描述（基础或升级）</summary>
        public string GetDescription(bool upgraded)
        {
            string desc = upgraded ? upgradeDescription : baseDescription;
            return string.IsNullOrWhiteSpace(desc) ? AutoGenerateDescription(upgraded) : desc;
        }

        /// <summary>获取当前效果列表（基础或升级）</summary>
        public List<CardEffect> GetEffects(bool upgraded)
        {
            if (cardType == CardType.Ability) return upgraded ? upgradeAbility.triggeredEffects : baseAbility.triggeredEffects;
            return upgraded ? upgradeEffects : baseEffects;
        }

        /// <summary>获取能力数据（基础或升级）</summary>
        public AbilityData GetAbility(bool upgraded) => upgraded ? upgradeAbility : baseAbility;

        /// <summary>自动生成描述</summary>
        public string AutoGenerateDescription(bool upgraded)
        {
            var sb = new StringBuilder();
            var effects = GetEffects(upgraded);

            if (cardType == CardType.Ability)
            {
                var ability = GetAbility(upgraded);
                sb.AppendLine(ability.GetDescription());
            }

            for (int i = 0; i < effects.Count; i++)
            {
                if (!effects[i].enabled) continue;
                sb.AppendLine($"{i + 1}. {effects[i].GetDescription()}");
            }

            if (existence != CardExistence.Normal)
            {
                sb.AppendLine(existence == CardExistence.BattleRemove ? "（战斗内移除）" : "（永久移除）");
            }

            return sb.ToString().TrimEnd();
        }

        // === 静态辅助 ===

        public static string GetGradeName(CardGrade g) => g switch
        {
            CardGrade.Bronze => "铜",
            CardGrade.Silver => "银",
            CardGrade.Gold => "金",
            _ => g.ToString()
        };

        public static string GetCardTypeName(CardType t) => t switch
        {
            CardType.Attack => "攻击",
            CardType.Skill => "技能",
            CardType.Ability => "能力",
            _ => t.ToString()
        };

        public static string GetExistenceName(CardExistence e) => e switch
        {
            CardExistence.Normal => "普通",
            CardExistence.BattleRemove => "战斗内移除",
            CardExistence.PermanentRemove => "永久移除",
            _ => e.ToString()
        };

        public static string GetKeywordName(CardKeyword k) => k switch
        {
            CardKeyword.None => "无",
            CardKeyword.Echo => "回响",
            CardKeyword.Calamity => "灾厄",
            CardKeyword.Fate => "命运",
            _ => k.ToString()
        };
    }
}
